# Generated by Django 4.2.11 on 2024-09-25 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxrate',
            name='exempt_products',
        ),
    ]
