# Generated by Django 4.2.11 on 2024-09-23 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderlineitems', to='product.productvariant'),
        ),
    ]
