# Generated by Django 4.2.11 on 2024-09-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderlineitem_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('last_name', 'first_name')},
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_default_delivery_address',
        ),
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('DSA', 'Default Shipping Address'), ('DBA', 'Default Billing Address'), ('SA', 'Shipping Address'), ('BA', 'Billing Address'), ('DSA_DBA', 'Default Shipping and Billing Address')], default='DSA_DBA', max_length=7),
        ),
    ]
