# Generated by Django 4.2.11 on 2024-09-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderlineitem_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due_amount',
            field=models.IntegerField(default=0),
        ),
    ]
