# Generated by Django 4.2.11 on 2024-09-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_due_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='due_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='is_due',
            field=models.BooleanField(default=True),
        ),
    ]
