# Generated by Django 4.2.11 on 2024-10-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_address_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_terms',
            new_name='payment_term',
        ),
    ]
