# Generated by Django 4.2.11 on 2024-10-06 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_preferred_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_discounted_amount',
            field=models.BigIntegerField(blank=True, help_text='Total amount of the order after applying discounts in cents, stored in the base currency.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='total_shipping_fee',
            field=models.BigIntegerField(blank=True, help_text='Total shipping amount of the order in cents, stored in the base currency.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='total_tax_amount',
            field=models.BigIntegerField(blank=True, help_text='Total tax amount of the order in cents, stored in the base currency.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
