# Generated by Django 4.2.11 on 2024-09-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_due',
        ),
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_terms',
            field=models.CharField(choices=[('DUE_ON_RECEIPT', 'Due on receipt'), ('DUE_ON_FULFILLMENT', 'Due on fulfillment'), ('DUE_ON_INSTALLMENT', 'Due on installment'), ('FIXED_DATE', 'Fixed date')], default='DUE_ON_RECEIPT', help_text='Represents the payment terms for the order.', max_length=32),
        ),
    ]
