# Generated by Django 4.2.11 on 2024-10-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_total_discounted_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_shipping_fee',
            new_name='total_shipping_cost',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_tax_amount',
            new_name='total_tax',
        ),
    ]
