# Generated by Django 4.2.11 on 2024-09-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_is_due_order_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='charge_status',
            field=models.CharField(choices=[('DUE', 'Due'), ('PARTIAL', 'Partially charged'), ('FULL', 'Fully charged'), ('OVERCHARGED', 'Overcharged')], default='DUE', help_text='Represents the charge status of the order based on transaction charges.', max_length=32, verbose_name='Charge Status'),
        ),
    ]
