# Generated by Django 4.2.11 on 2024-09-05 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(blank=True, help_text='Name of the company.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site',
            field=models.OneToOneField(blank=True, help_text='The site this configuration applies to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
