# Generated by Django 4.2.11 on 2024-10-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_alter_promocode_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='active',
            new_name='is_active',
        ),
    ]
