# Generated by Django 4.2.11 on 2024-09-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingrate',
            name='city',
            field=models.CharField(blank=True, help_text="Specific city within a delivery region, e.g., 'San Francisco'.", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='region',
            field=models.CharField(blank=True, help_text="Specific region within a country, e.g., 'California'. If blank, the rate applies nationwide.", max_length=200, null=True),
        ),
    ]
