# Generated by Django 4.2.11 on 2024-09-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shippingrate_city_alter_shippingrate_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingrate',
            name='city',
            field=models.CharField(blank=True, help_text="Specific city within the region, e.g., 'San Francisco'.", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='region',
            field=models.CharField(blank=True, help_text="Region within the country, e.g., 'California'. If blank, applies nationwide.", max_length=200, null=True),
        ),
    ]
