# Generated by Django 4.2.11 on 2024-07-29 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='image',
        ),
    ]
