# Generated by Django 4.2.11 on 2024-10-03 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_tax_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='The name of the product.', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(help_text='The type of product.', on_delete=django.db.models.deletion.PROTECT, related_name='product', to='product.producttype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(help_text='A brief summary of the product.', max_length=500),
        ),
    ]
