# Generated by Django 4.2.11 on 2024-07-29 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_initial'),
        ('product', '0003_remove_collection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filemanager.image'),
        ),
    ]
