# Generated by Django 4.2.11 on 2024-08-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_collection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('GRAM', 'Gram'), ('KG', 'Kilogram'), ('LB', 'Pound'), ('OZ', 'Ounce'), ('TON', 'Ton')], max_length=5, null=True),
        ),
    ]
