# Generated by Django 4.2.11 on 2024-10-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_name_alter_product_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='track_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
