# Generated by Django 4.2.11 on 2024-10-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productvariant_track_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='allow_backorder',
            field=models.BooleanField(default=False, help_text='Allow orders even if out of stock.'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='low_stock_threshold',
            field=models.IntegerField(default=0, help_text='Threshold to trigger low stock alert.', verbose_name='Stock'),
        ),
    ]
