# Generated by Django 4.2.11 on 2024-10-11 10:06

from django.db import migrations, models
import nxtbn.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productvariant_dimensions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='internal_metadata',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='metadata',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='A JSON field to store custom attributes for the variant. Primary attributes include color code, dimension, and weight value. Weight value and dimension are used for shipping calculations. This field allows adding as many custom attributes as needed.', null=True, validators=[nxtbn.core.models.no_nested_values]),
        ),
    ]
