# Generated by Django 4.2.11 on 2024-09-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('PAYPAL', 'PayPal'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH_ON_DELIVERY', 'Cash on Delivery'), ('GIFT_CARD', 'Gift Card'), ('DIRECT_DEBIT', 'Direct Debit'), ('CASH_IN_STORE', 'Cash in Store'), ('MFS', 'Mobile Financial Services'), ('CARRIER_BILLING', 'Carrier Billing'), ('CRYPTOCURRENCY', 'Cryptocurrency'), ('BUY_NOW_PAY_LATER', 'Buy Now, Pay Later'), ('E_WALLET', 'E-Wallet'), ('BANK_TRANSFER_INSTANT', 'Instant Bank Transfer'), ('POSTAL_MONEY_ORDER', 'Postal Money Order'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=25),
        ),
    ]
