# Generated by Django 4.2.11 on 2024-09-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELED', 'Canceled'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('UNDER_REVIEW', 'Under Review'), ('PENDING', 'Pending')], default='AUTHORIZED', max_length=20),
        ),
    ]
